/**
 * Save function - returns null for server-side rendering.
 * The block output is generated by render_jukebox_block() in PHP.
 *
 * @return {null} Null for server-side rendering.
 */
export default function save() {
	return null;
}


